version: 0.2

phases:
  pre_build:
    commands:
      # Install Node.js 16.x
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - ng build --prod

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/sturdy-currency-dashboard
