version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18.x
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - cd dist/sturdy-currency-dashboard
      - ls -la
      - aws s3 sync --delete . s3://sturdy-currency
