version: 0.2

phases:
  pre_build:
    commands:
      - nvm install 16.13.0
      - nvm use 16.13.0
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - ng build --prod

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/sturdy-currency-dashboard
